name: Run Crypto Twitter Bot

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install tweepy

      - name: Debug Secrets
        run: |
          echo "CONSUMER_KEY=${{ secrets.CONSUMER_KEY }}" | sed 's/./& /g'
          echo "CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }}" | sed 's/./& /g'
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" | sed 's/./& /g'
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" | sed 's/./& /g'

      - name: Run the bot
        run: python bot.py
